data = {
    "Place": "放置",
    "Transform Pro": "变换加强版",
    "Dynamic Place": "动态放置",
    "Stop When Intersecting": "碰撞时候停止",
    "Keep Color When Intersecting": "碰撞时不变颜色",
    "Collision Alert": "碰撞警告",
    "Invert Axis": "反转轴",
    "Trace Collection Level": "追溯父级集合深度",
    "Draw Active Collision": "绘制激活项目碰撞",
    "Draw Active Object Collision lines, Performance will decrease": "绘制激活项目碰撞线，性能会下降",
    "Scale\nShift: Duplicate\nAlt: Set Axis": "缩放\nShift: 复制\nAlt: 设置轴",
    "Rotate\nShift: Duplicate\nAlt: Set Axis": "旋转\nShift: 复制\nAlt: 设置轴",
    "Please select the active object": "请选择一个物体为激活项",
    "Place Tool": "放置工具",
    "Use Color When Moving": "运行时变色",
    "Gizmo Handle All Event": "Gizmo 接收所有按键",
    "Active Instance Bounding Box": "活动项实例碰撞盒",
    "Consider Scene Geo Nodes Instance": "评估场景几何节点实例",
    "Use visual obj bounding box, slower": "使用可视化物体碰撞盒，速度慢一些",
    "Use basic mesh bounding box, faster": "使用基础网格碰撞盒，速度快一些",
    "Scene Objects": "场景物体",
    "Adsorption Angle": "吸附角度",
    "Set Place Axis": "设置放置轴",
    "Bake Animation": "烘焙动画",
    "Use Local Rotate": "使用局部旋转",
    "Press D to switch Z-axis adjustment mode": "按下 D 切换Z轴调整模式",
    "Z-axis adjustment:": "Z轴调整:",
    "R: Press Reset Rotation": "R: 按下重置旋转",
    "Z: Press Reset Z Offset": "Z: 按下重置Z偏移",
    "Rotate:": "旋转:",
    "Z Offset:": "Z 偏移:",
    "Not in User Keymap Found %s": "在用户快捷键中未找到 %s",
    "Show Place Axis": "显示放置轴",
    "Press D adjustment Z-offset": "按 D 调整Z偏移",
    "Adsorption Z Offset": "吸附Z偏移",
    "Transform Tool": "变换工具",
    "Transform Gizmo circle size": "变换 Gizmo 圆大小",
    "Press Right or ESC to cancel setting the axis": "按 右键或ESC 取消设置轴",
    "Circle size": "圆大小",
    "Arrow Offset": "箭头偏移",
    "Arrow Length": "箭头长度",
    "Avoid moving during quick selections, if you don't follow, you can adjust the values to achieve the best results": "避免在快速选择时进行了移动操作,如果不跟手可以调整数值以达最佳",
    "Move Event Count": "移动事件计数",
    "By Center": "按中心",
    "By Individual Center": "按各自中心",
    "Force Field Mode": "力场模式",
    "Attenuation factor": "衰减系数",
    "Attenuation coefficient of force field movement": "力场运动的衰减系数",
    "Min Force Field": "最小力场",
    "Max Force Field": "最大力场",
    "Force Field Dynamic Place": "力场动态放置",
    "Gravity Dynamic Place": "重力动态放置",
    "Gizmo Alpha Vary": "Gizmo Alpha变化"
}
